# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/maucher/Desktop/EN217_Processor/vivado/project_1/project_1.srcs/sources_1/ip/Clock_manager/Clock_manager.xci
# IP: The module: 'Clock_manager' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/maucher/Desktop/EN217_Processor/vivado/project_1/project_1.srcs/sources_1/ip/Clock_manager/Clock_manager_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_manager'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/maucher/Desktop/EN217_Processor/vivado/project_1/project_1.srcs/sources_1/ip/Clock_manager/Clock_manager.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_manager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/maucher/Desktop/EN217_Processor/vivado/project_1/project_1.srcs/sources_1/ip/Clock_manager/Clock_manager_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_manager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/maucher/Desktop/EN217_Processor/vivado/project_1/project_1.srcs/sources_1/ip/Clock_manager/Clock_manager.xci
# IP: The module: 'Clock_manager' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/maucher/Desktop/EN217_Processor/vivado/project_1/project_1.srcs/sources_1/ip/Clock_manager/Clock_manager_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_manager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/maucher/Desktop/EN217_Processor/vivado/project_1/project_1.srcs/sources_1/ip/Clock_manager/Clock_manager.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_manager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/maucher/Desktop/EN217_Processor/vivado/project_1/project_1.srcs/sources_1/ip/Clock_manager/Clock_manager_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clock_manager'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
