# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/maucher/Desktop/EN217_Processor/vivado/Proco_8b/Proco_8b.cache/wt [current_project]
set_property parent.project_path C:/Users/maucher/Desktop/EN217_Processor/vivado/Proco_8b/Proco_8b.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/maucher/Desktop/EN217_Processor/src/UT/ALU.vhd
  C:/Users/maucher/Desktop/EN217_Processor/test_bench/tb_alu.vhd
}
read_xdc C:/Users/maucher/Desktop/EN217_Processor/vivado/Proco_8b/Proco_8b.srcs/constrs_1/imports/src/Nexys4_CPU.xdc
set_property used_in_implementation false [get_files C:/Users/maucher/Desktop/EN217_Processor/vivado/Proco_8b/Proco_8b.srcs/constrs_1/imports/src/Nexys4_CPU.xdc]

synth_design -top alu_tb -part xc7a100tcsg324-1
write_checkpoint -noxdef alu_tb.dcp
catch { report_utilization -file alu_tb_utilization_synth.rpt -pb alu_tb_utilization_synth.pb }
